name: hans andresen chocolates
favicon: null
layout_spectrum: 0.31501
typography_spectrum: 0.54513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#431903'
    - '#b5a9a1'
    - '#897068'
    - '#5f4f41'
  brandStrength: 0.5
  lightness: 0.24753418238833547
  saturation: 0.12226111302152276
  rhythmicContrast: 0.2972381981089711
purpose: []
