name: hans andresen chocolates
favicon: null
layout_spectrum: 0.31501
typography_spectrum: 0.9818422121461481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f7fa'
    - '#845943'
    - '#683626'
    - '#abaaa8'
    - '#8e8783'
  brandStrength: 0.3125
  lightness: 0.24753418238833547
  saturation: 0.12226111302152276
  rhythmicContrast: 0.2972381981089711
purpose: []
