favicon: null
name: hans andresen chocolates
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 1
  lightness: 0.8924731
  brandColors:
    - '#FFFFFF'
    - '#431803'
    - '#5A4A42'
    - '#89665B'
    - '#9B8F86'
  rhythmicContrast: 0.5
typography_spectrum: 0.54513
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
