favicon: null
name: hans andresen chocolates
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 1
  lightness: 0.8924731
  brandColors:
    - '#FFFFFF'
    - '#898989'
    - '#431903'
    - '#C2B5AE'
    - '#7A5D4E'
  rhythmicContrast: 0.5
typography_spectrum: 0.54513
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
