name: hans andresen chocolates
favicon: null
layout_spectrum: 0.2995459472294897
typography_spectrum: 0.9818422121461481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6944067301228642
  lightness: 0.24753418238833547
  saturation: 0.12226111302152276
  rhythmicContrast: 0.2972381981089711
purpose: []
